spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/notification_poc
spring.datasource.username=postgres
spring.datasource.password=@dm!n

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# mail config - mailtrap.io is a fake SMTP server for testing
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=656e49987219db
spring.mail.password=6d3472e7d86a32
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true